### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [RowdyBeiBei/Nokkangken#18]
mind you, if you scatter your sql files across the app, rather than keeping it all within your db/sql structure, you are losing the ability to quickly switch the schema, which may catch up with you :wink:

i.e. centralized use of type `QueryFile` (within your sql/index.js) is always the best :wink:

**Comment by Gildilocks** [comment]
Hi! Thanks for your comment (and also for your general activity in answering questions across the internet--I'm doing quite a bit of learning as I go, and your explanations have been very helpful)! 

This is actually something I was wondering about--I wasn't sure what the ideal way to implement initializing our database/create the tables/add any dummy data we might want. Initially I tried to just call all the individual drop/create/init functions that have been extended on to the database from some sort of init file, eg:
```javascript
var db = require('./database').db;

db.users.drop()
.then( db.scheduleds.drop)
.then( db.possibles.drop)
...
.then(db.users.create)
.then( db.scheduleds.create)
.then( db.possibles.create)
...
.then(db.users.init);
```

This seemed a little messy to me which prompted me to create seperate sql files in a different directory that just held all of these initial functions in one place. This seems to defeat the purpose of the overall modular use of the database, so I'm not really happy with it either.

I suppose my question, then, is: Is the above example a reasonable way to initialize the database? Is there a similar, but better, way to do this?

**Comment by vitaly-t** [comment]
The only improvement I can think of - placing it all inside a transaction, since you are doing multiple changes to the database ;)

```js
db.tx(function (t) {
    return t.batch([
        t.users.drop(),
        t.scheduleds.drop(),
        t.possibles.drop(),
        t.users.create(),
        t.scheduleds.create(),
        t.possibles.create(),
        t.users.init()
    ]);
})
    .then(function (data) {
        // SUCCESS, transaction committed
    })
    .catch(function (error) {
        // ERROR, transaction rolled back
    });
```

Then you do not need to use one global script, and you do not need to use `BEGIN` / `COMMIT` / `ROLLBACK` there, it is all provided automatically in this case by method `tx`.

You you will keep your modulation this way ;)

**Comment by Gildilocks** [comment]
Thanks for your help! I like the design you laid out in your demo, and (as you likely noticed) am trying to implement that design strategy in our project.

While it is fairly straightforward for simple database interactions, when more complex requests to our database come in to play, given the modular nature of the design, there seem to three different places at which the behavior can be controlled--in particular in situations where chains of dependent queries/subqueries might be required:

1. In the sequel file/query itself--while this isn't always possible, in some cases more complex queries can be constructed in sql to return the desired results.
2. In the repo that defines the function that will be extended to the database -- the function defined on the repo could be composed of a task, rather than a single query.
3. On the server level where the database's methods are being called--being able to use tasks here seems to be one of the goals of this design scheme, so I would expect to potentially create multi-query tasks here as necessary; however, it seems that this could be done at the query/repo level as well. 

While our project is perhaps not far along enough for this issue to be a problem, I was wondering if you might have any recommendations about the use cases/best practices regarding the list above. For example, I can see the appeal of keeping things at the query level fairly basic and composing more complex actions out of a set of basic queries; however, this seems like it could be less efficient at times while also underutilizing the power of the sql language. There may not be a 'right' answer to this, as I imagine it depends on some extent to the specifics of the project, but I'd be interested to hear your thoughts!

**Comment by vitaly-t** [comment]
This all depends on how scalable you system needs to be ;) Have you seen this? - https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost

There are always different levels of optimization, depending on the requirements ;)

**Comment by Gildilocks** [comment]
Hi again! I think I'm starting to understand how these things work (maybe)!

I do have a question about chaining queries inside of transactions--ie pass the return value from one query to another query/set of queries all within a single transaction.

Here's an example--it updates the database the way I want, but having read a lot of what you've written, I feel like there's probably a better way to do it that I just can't figure out. The basic idea is that a new row is inserted in one table, returning an id which is then used as a reference in each of a collection of rows that are subsequently created in another table. 

```javascript
//body input is {time: time, facebookId: facebookId, locations: [busId1, busId2...]}
exports.addPossibleEvent = (req, res) => {
  db.tx(t=>{
    return t.possibles.add({eventTime: +req.body.time, facebookId: +req.body.facebookId})
      .then(p => {
        return t.batch(req.body.locations.map(businessId => {
          t.possibleLocations.add({businessId: businessId, possibleId: p.id});
        }));
      });
  })
  .then(data=> res.status(201).send(data))
  .catch(error=> res.status(409).send(error));
};
```

Additionally, the data being sent back (while not particularly important) is just an array of 'null' values equal to the amount of inserts in the second table (ie, the same length as the 'locations' input array).  How would I get it to return actual values--I feel like this might happen automatically if I implement the whole thing a better way?

**Comment by vitaly-t** [comment]
The method looks fine, assuming it is a method within one of your repositories :wink:

Method `batch` gives you the values according to what method `possibleLocations.add` resolves with, obviously, so in your case it seems to be resolving with `null`. It's all just basic promise logic :wink:

**Comment by vitaly-t** [comment]
Actually, on the second look, you do have a problem there...

this code:
```js
return t.batch(req.body.locations.map(businessId => {
          t.possibleLocations.add({businessId: businessId, possibleId: p.id});
        }));
```
should be either this:
```js
return t.batch(req.body.locations.map(businessId => 
          t.possibleLocations.add({businessId: businessId, possibleId: p.id});
        ));
```

or this:

```js
return t.batch(req.body.locations.map(businessId => {
          return t.possibleLocations.add({businessId: businessId, possibleId: p.id});
        }));
```

i.e. you absolutely must return the result of calling `t.possibleLocations.add`, because this is what method `batch` is supposed to resolve - an array of promises.

Otherwise it won't even work correctly, as failure to chain promises will result in loose promises and thus failed queries.

**Comment by Gildilocks** [comment]
Weird, it was updating the database before when the t.possibleLocations.add result wasn't being returned--not sure how this worked if it should have caused the queries to fail. 

However, I changed it to actually return the values, and now it both works and the data returned by the transaction isn't null. Excellent! Thanks again for being so helpful!

**Comment by vitaly-t** [comment]
> Weird, it was updating the database before when the t.possibleLocations.add result wasn't being returned--not sure how this worked if it should have caused the queries to fail.

Actually, it is not weird, it works as expected because you do not have any failure. If one of your queries in the batch fails, then you would see the problem right away, i.e. the old code would throw errors about loose queries.

This is the general trick about promises, all looks good without providing `.catch`, while nothing throws errors, but when it does, and you did not chain you promises into your final `.catch` - hell breaks loose :wink:

**Comment by Gildilocks** [comment]
Aaah, that makes sense! I guess I should probably handle the errors :)! Thanks!

**Comment by vitaly-t** [comment]
>  I guess I should probably handle the errors

You absolutely should, and you do, after applying the change I suggested :wink:

The rest looks fine :wink:

**Comment by vitaly-t** [comment]
Looking at the code, you are doing well :wink:

I hope you are using option `debug` of the `QueryFile`, it is indispensable for development :wink:
